### ISSUE TITLE
Bump dependencies to compile with GHC 7.10

### ISSUE THREAD

**Issue by jimenezrick** [well-typed/ghc-events-analyze#12]
Update dependencies versions in order to compile with GHC 7.10.

**Comment by jimenezrick** [comment]
I could get rid of most compile errors using the `master` brach of `ghc-events` and `th-lift` from GitHub. But I still have issues getting to find the right version of: `SVGFonts`, `diagrams-*`

**Comment by edsko** [comment]
It would probably need updating for diagrams 1.3, which works with 7.10. The 1.2 series of diagrams is not yet updated for 7.10.

**Comment by edsko** [comment]
(But diagrams 1.3 has some backwards incompatible changes so updating to 1.3 is not entirely trivial, although not too hard.)

**Comment by robstewart57** [comment]
There's another reason why bumping to GHC 7.10 is slightly more than a relaxation of versions.

```
src/GHC/RTS/Events/Analyze/Script.hs:198:10:
    Duplicate instance declarations:
      instance Lift Word32
        -- Defined at src/GHC/RTS/Events/Analyze/Script.hs:198:10
      instance Lift Word32 -- Defined in ‘Language.Haskell.TH.Syntax’
```

From template-haskell 2.10.0.0, packaged with ghc 7.10, this instance is already defined. Added here https://github.com/ghc/ghc/commit/c190b73f972abdeefc48469eb7c23837f43b3425 .

**Comment by edsko** [comment]
Sounds like an `#ifdef` will sort that out? Or are they incompatible?

**Comment by WillSewell** [comment]
I have patched the program to work with GHC 7.10.

I can make a PR, although I'm not sure if I should introduce a bunch of `#ifdef` to keep it backwards compatible. I'll make the PR, and see what you think would be best.

**Comment by bitemyapp** [comment]
@WillSewell it's pretty standard to use CPP to deal with multi-GHC/library compat.

**Comment by WillSewell** [comment]
OK, I went for that option. Let me know what you think. https://github.com/well-typed/ghc-events-analyze/pull/15

**Comment by WillSewell** [comment]
We can close this now.

**Comment by edsko** [comment]
Indeed. Thanks :)
