### ISSUE TITLE
Fails to open SVG font file

### ISSUE THREAD

**Issue by jimenezrick** [well-typed/ghc-events-analyze#13]
When executing ghc-events-analyze it says:

```
ghc-events-analyze: /home/ricardo/.cabal/share/x86_64-linux-ghc-7.6.3/SVGFonts-1.4.0.3/fonts/LinLibertine.svg: hGetContents: invalid argument (invalid byte sequence)
```

Not sure if this error comes from `ghc-events-analyze` or `SVGFonts`. Tested with Haskell platform using GHC (7.6.3).

**Comment by jimenezrick** [comment]
Also, replacing the content of `LinLibertine.svg` by another bundled font makes it work.

**Comment by edsko** [comment]
That's really weird, that's a standard diagrams font, ghc-events-analyze doesn't do anything special there..

**Comment by jimenezrick** [comment]
OK, in that case the bug is not here. Thanks!
