### ISSUE TITLE
Rendering unlike blogpost..

### ISSUE THREAD

**Issue by clojj** [well-typed/ghc-events-analyze#19]
This is SVG produced on a Mac and on Ubuntu.
How can I get the beautiful and readable square-rendering for each bucket ?
On my machine(s) each bucket is just a very slim rectangle and does not fill an entire time-line section like in your blog-post.

![screenshot from 2016-06-12 21-56-30](https://cloud.githubusercontent.com/assets/4367963/15993499/9d8536f0-30e8-11e6-998d-03a3d0198e9e.png)

**Comment by edsko** [comment]
What are you using to display the SVGs? I seem to recall that not all applications display them equally well. Try some different ones and see if that helps?

**Comment by clojj** [comment]
I tried 3 different browsers, and 2 other native/java applications... it was never rendered with squares, always rectangles streched vertically

**Comment by edsko** [comment]
Reproduced. I will see if I can do something about this.

**Comment by edsko** [comment]
Ok. I've fixed this now. See the README at https://github.com/well-typed/ghc-events-analyze for some example output and the command line arguments that were used to generate those pictures. Not yet released, want to fix the windowing as well, but will hopefully release soon. Meanwhile can build from the repo, of course.
