### ISSUE TITLE
Make it easy to filter finaliser threads out

### ISSUE THREAD

**Issue by pepeiborra** [well-typed/ghc-events-analyze#26]
Finalizer threads clobber the view when present, since their number is proportional to the number of collections and can be quite large.

Unfortunately there is no easy way to filter them out. labelThreadId can be used on a finaliser body, but finaliser threads get reused sometimes and as it turns out labelThreadId is not idempotent: labels get appended.

I don't see any mention of finalisers in the AST defined by ghc-events so perhaps this ticket should be raised in the ghc-events issue tracker or even in the GHC issue tracker, but I thought I'd ask here first.

**Comment by pepeiborra** [comment]
Correction, my understanding of how labelThread works was not accurate. It is ghc-events-analyze that appends labels. 

I suppose the best way to filter them out is to extend the report language with a filtering construct a la WHERE ?

**Comment by edsko** [comment]
Sure, such a PR would be welcome :)

**Comment by pepeiborra** [comment]
PR sent :)

**Comment by edsko** [comment]
Closed in #27 .
