### ISSUE TITLE
ghc-events-analyze is not buildable with ghc-events >= 0.13

### ISSUE THREAD

**Issue by Shimuuar** [well-typed/ghc-events-analyze#34]
It changed types of few fields from `String` to `Text` which obviously breaks build

It would be nice to update version constraints on hackage

**Comment by maoe** [comment]
I have a branch that supports the new API. I’ll send a PR later today.

**Comment by maoe** [comment]
Sent https://github.com/well-typed/ghc-events-analyze/pull/35.

Even after it's merged, the version constraints on ghc-events for existing releases need updating.

**Comment by edsko** [comment]
Closed in #35 .
